"""Init

Revision ID: 275c46f209b9
Revises: 
Create Date: 2021-09-08 16:24:57.183867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '275c46f209b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('glasovi', 'ucesnikId',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('glasovi', 'ucesnikId',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
