"""ucesnikID zamenjen sa rbUcesnika u tabeli Glas

Revision ID: b5e9b354bbe3
Revises: 865afcc49100
Create Date: 2021-09-09 12:50:03.683154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5e9b354bbe3'
down_revision = '865afcc49100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glasovi', sa.Column('rbUcesnika', sa.Integer(), nullable=True))
    op.drop_column('glasovi', 'ucesnikId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glasovi', sa.Column('ucesnikId', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('glasovi', 'rbUcesnika')
    # ### end Alembic commands ###
